//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gerenciamento_hotelEntities : DbContext
    {
        public gerenciamento_hotelEntities()
            : base("name=gerenciamento_hotelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_acomodacao> tb_acomodacao { get; set; }
        public virtual DbSet<tb_checkin> tb_checkin { get; set; }
        public virtual DbSet<tb_checkout> tb_checkout { get; set; }
        public virtual DbSet<tb_consumo> tb_consumo { get; set; }
        public virtual DbSet<tb_funcionario> tb_funcionario { get; set; }
        public virtual DbSet<tb_hospede> tb_hospede { get; set; }
        public virtual DbSet<tb_hospede_checkin> tb_hospede_checkin { get; set; }
        public virtual DbSet<tb_itens_consumo> tb_itens_consumo { get; set; }
        public virtual DbSet<tb_reserva> tb_reserva { get; set; }
    }
}
