//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_checkin
    {
        public tb_checkin()
        {
            this.tb_checkout = new HashSet<tb_checkout>();
            this.tb_consumo = new HashSet<tb_consumo>();
            this.tb_hospede_checkin = new HashSet<tb_hospede_checkin>();
        }
    
        public int codigo { get; set; }
        [Display(Name = "Data de Entrada")]
        public Nullable<System.DateTime> data_entrada { get; set; }
        [Display(Name = "Hora de Entrada")]
        public string hora_entrada { get; set; }
        [Display(Name = "Data de Saída")]
        public Nullable<System.DateTime> data_saida { get; set; }
        [Display(Name = "Hora de Saída")]
        public string hora_saida { get; set; }
        public int codigo_hospede { get; set; }
        public int codigo_acomodacao { get; set; }
        [Display(Name = "Diária (R$)")]
        public Nullable<decimal> valor_diaria { get; set; }
        public int codigo_funcionario { get; set; }
        [Display(Name = "Status")]
        public Nullable<short> status { get; set; }
        [Display(Name = "Qtd Adultos")]
        public Nullable<int> qtd_adultos { get; set; }
        [Display(Name = "Qtd Crianças")]
        public Nullable<int> qtd_criancas { get; set; }
    
        public virtual tb_acomodacao tb_acomodacao { get; set; }
        public virtual tb_funcionario tb_funcionario { get; set; }
        public virtual tb_hospede tb_hospede { get; set; }
        public virtual ICollection<tb_checkout> tb_checkout { get; set; }
        public virtual ICollection<tb_consumo> tb_consumo { get; set; }
        public virtual ICollection<tb_hospede_checkin> tb_hospede_checkin { get; set; }
    }
}
