//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_consumo
    {
        public int codigo { get; set; }
        [Display(Name = "Data do Consumo")]
        public string data_consumo { get; set; }
        public int codigo_checkin { get; set; }
        public int codigo_item_consumo { get; set; }
        [Display(Name = "Quantidade")]
        public Nullable<int> quantidade { get; set; }
        [Display(Name = "Valor Unitário")]
        public Nullable<decimal> valor_unitario { get; set; }
        [Display(Name = "Valor Total")]
        public Nullable<decimal> valor_final { get; set; }
    
        public virtual tb_checkin tb_checkin { get; set; }
        public virtual tb_itens_consumo tb_itens_consumo { get; set; }
    }
}
