//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_funcionario
    {
        public tb_funcionario()
        {
            this.tb_checkin = new HashSet<tb_checkin>();
        }
    
        public int codigo { get; set; }
        [Display(Name = "Funcionário")]
        public string nome { get; set; }
        [Display(Name = "Endereço")]
        public string endereco { get; set; }
        [Display(Name = "Telefone")]
        public string telefone { get; set; }
        [Display(Name = "Doc. Identif.")]
        public string documento_identificacao { get; set; }
        [Display(Name = "Tipo Documento")]
        public Nullable<short> tipo_documento_identificacao { get; set; }
        [Display(Name = "Data de Nascimento")]
        public Nullable<System.DateTime> data_nascimento { get; set; }
        [Display(Name = "Tipo")]
        public Nullable<int> tipo_usuario { get; set; }
        [Display(Name = "Senha")]
        public string senha { get; set; }
    
        public virtual ICollection<tb_checkin> tb_checkin { get; set; }
    }
}
