//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_hospede_checkin
    {
        public int codigo { get; set; }
        public int codigo_checkin { get; set; }
        public int codigo_hospede { get; set; }
    
        public virtual tb_checkin tb_checkin { get; set; }
        public virtual tb_hospede tb_hospede { get; set; }
    }
}
