//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_hospede
    {
        public tb_hospede()
        {
            this.tb_checkin = new HashSet<tb_checkin>();
            this.tb_hospede_checkin = new HashSet<tb_hospede_checkin>();
            this.tb_reserva = new HashSet<tb_reserva>();
        }
    
        public int codigo { get; set; }
        [Display(Name = "Hóspede")]
        public string nome { get; set; }
        [Display(Name = "Endereço")]
        public string endereco { get; set; }
        [Display(Name = "E-mail")]
        public string email { get; set; }
        [Display(Name = "Doc. Identif.")]
        public string documento_identificacao { get; set; }
        [Display(Name = "Tipo Doc.")]
        public Nullable<short> tipo_documento_identificacao { get; set; }
        [Display(Name = "Data de Nascimento")]
        public Nullable<System.DateTime> data_nascimento { get; set; }
        [Display(Name = "Filiação")]
        public string nome_pai_mae { get; set; }
    
        public virtual ICollection<tb_checkin> tb_checkin { get; set; }
        public virtual ICollection<tb_hospede_checkin> tb_hospede_checkin { get; set; }
        public virtual ICollection<tb_reserva> tb_reserva { get; set; }
    }
}
