//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GerenciamentoHotel.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_reserva
    {
        public int codigo { get; set; }
        public int codigo_hospede { get; set; }
        [Display(Name = "Data de Entrada")]
        public Nullable<System.DateTime> data_entrada { get; set; }
        [Display(Name = "Data de Saída")]
        public Nullable<System.DateTime> data_saida { get; set; }
        public int codigo_acomodacao { get; set; }
        [Display(Name = "Qtd Adultos")]
        public Nullable<int> qtd_adultos { get; set; }
        [Display(Name = "Qtd Crianças")]
        public Nullable<int> qtd_criancas { get; set; }
    
        public virtual tb_acomodacao tb_acomodacao { get; set; }
        public virtual tb_hospede tb_hospede { get; set; }
    }
}
